// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(IndoPlantDb))]
    [Migration("20240505141612_added_DocumentResult")]
    partial class added_DocumentResult
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Concrete.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Entities.Concrete.DocumentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantChatGPTResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantGlobalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoboflowJsonModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentResults");
                });

            modelBuilder.Entity("Entities.Concrete.ImageDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Copyright")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentResultId")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentResultId1")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentResultId2")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentResultId3")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentResultId");

                    b.HasIndex("DocumentResultId1");

                    b.HasIndex("DocumentResultId2");

                    b.HasIndex("DocumentResultId3");

                    b.ToTable("ImageDetail");
                });

            modelBuilder.Entity("Entities.Concrete.PlantCoordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DocumentResultId")
                        .HasColumnType("int");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentResultId");

                    b.ToTable("PlantCoordinate");
                });

            modelBuilder.Entity("Entities.Concrete.RoboflowResponse", b =>
                {
                    b.Property<int>("RoboflowResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoboflowResponseId"), 1L, 1);

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("Confidence")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoboflowResponseId");

                    b.ToTable("RoboflowResponses");
                });

            modelBuilder.Entity("Entities.Concrete.ImageDetail", b =>
                {
                    b.HasOne("Entities.Concrete.DocumentResult", null)
                        .WithMany("PlantBarkImages")
                        .HasForeignKey("DocumentResultId");

                    b.HasOne("Entities.Concrete.DocumentResult", null)
                        .WithMany("PlantFlowerImages")
                        .HasForeignKey("DocumentResultId1");

                    b.HasOne("Entities.Concrete.DocumentResult", null)
                        .WithMany("PlantFruitImages")
                        .HasForeignKey("DocumentResultId2");

                    b.HasOne("Entities.Concrete.DocumentResult", null)
                        .WithMany("PlantLeafImages")
                        .HasForeignKey("DocumentResultId3");
                });

            modelBuilder.Entity("Entities.Concrete.PlantCoordinate", b =>
                {
                    b.HasOne("Entities.Concrete.DocumentResult", null)
                        .WithMany("PlantCoordinates")
                        .HasForeignKey("DocumentResultId");
                });

            modelBuilder.Entity("Entities.Concrete.DocumentResult", b =>
                {
                    b.Navigation("PlantBarkImages");

                    b.Navigation("PlantCoordinates");

                    b.Navigation("PlantFlowerImages");

                    b.Navigation("PlantFruitImages");

                    b.Navigation("PlantLeafImages");
                });
#pragma warning restore 612, 618
        }
    }
}
